### ISSUE TITLE
Metodo multiplicar clase fraccion

### ISSUE THREAD

**Issue by cijaraadrian** [cijaraadrian/IWVG.SwC.cijaraadrian#4]
Se desea poder obtener el producto de 2 fracciones

Para mas informacion consultar la [Wiki](https://github.com/cijaraadrian/IWVG.SwC.cijaraadrian/wiki)

**Comment by zuldare** [comment]
Issue#04  arreglado.
Merge rama issue#04 con develop hecha
He cambiado en la clase FractionTest la declaración de private Fraction _Obj_ --> private Fraction _obj_  (en java por convención las variables no empiezan con mayúsculas)
